// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTop.h for the primary calling header

#ifndef VERILATED_VTOP_TAGBUFFER_H_
#define VERILATED_VTOP_TAGBUFFER_H_  // guard

#include "verilated.h"
#include "verilated_threads.h"
#include "verilated_save.h"


class VTop__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTop_TagBuffer final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VlUnpacked<CData/*7:0*/, 32> __PVT__penc__DOT__gen__BRA__1__KET____DOT__s;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__16__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__16__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__17__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__17__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__18__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__18__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__19__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__19__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__20__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__20__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__21__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__21__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__22__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__22__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__23__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__23__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__24__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__24__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__25__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__25__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__26__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__26__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__27__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__27__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__28__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__28__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__29__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__29__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__30__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__30__KET____DOT__gen2__BRA__3__KET____DOT__mux;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 4> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__31__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 5> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__31__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<SData/*11:0*/, 16> __PVT__penc__DOT__gen__BRA__2__KET____DOT__s;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 2> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__0__KET____DOT__mux;
    };
    struct {
        VlUnpacked<CData/*1:0*/, 3> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 4> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*1:0*/, 5> __PVT__penc__DOT__gen__BRA__2__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<SData/*15:0*/, 8> __PVT__penc__DOT__gen__BRA__3__KET____DOT__s;
        VlUnpacked<CData/*2:0*/, 2> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 3> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 4> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 5> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 2> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 3> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 4> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 5> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 2> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 3> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 4> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 5> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 2> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 3> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 4> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 5> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 2> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 3> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 4> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 5> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 2> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 3> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 4> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 5> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 2> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 3> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 4> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 5> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 2> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 3> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 4> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*2:0*/, 5> __PVT__penc__DOT__gen__BRA__3__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<IData/*19:0*/, 4> __PVT__penc__DOT__gen__BRA__4__KET____DOT__s;
        VlUnpacked<CData/*3:0*/, 2> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 3> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 4> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 5> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 2> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 3> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 4> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 5> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 2> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 3> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 4> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 5> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 2> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 3> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 4> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*3:0*/, 5> __PVT__penc__DOT__gen__BRA__4__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<IData/*23:0*/, 2> __PVT__penc__DOT__gen__BRA__5__KET____DOT__s;
        VlUnpacked<CData/*4:0*/, 2> __PVT__penc__DOT__gen__BRA__5__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*4:0*/, 3> __PVT__penc__DOT__gen__BRA__5__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*4:0*/, 4> __PVT__penc__DOT__gen__BRA__5__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*4:0*/, 5> __PVT__penc__DOT__gen__BRA__5__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<CData/*4:0*/, 2> __PVT__penc__DOT__gen__BRA__5__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*4:0*/, 3> __PVT__penc__DOT__gen__BRA__5__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*4:0*/, 4> __PVT__penc__DOT__gen__BRA__5__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*4:0*/, 5> __PVT__penc__DOT__gen__BRA__5__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        VlUnpacked<IData/*27:0*/, 1> __PVT__penc__DOT__gen__BRA__6__KET____DOT__s;
        VlUnpacked<CData/*5:0*/, 2> __PVT__penc__DOT__gen__BRA__6__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__0__KET____DOT__mux;
    };
    struct {
        VlUnpacked<CData/*5:0*/, 3> __PVT__penc__DOT__gen__BRA__6__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*5:0*/, 4> __PVT__penc__DOT__gen__BRA__6__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__2__KET____DOT__mux;
        VlUnpacked<CData/*5:0*/, 5> __PVT__penc__DOT__gen__BRA__6__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__3__KET____DOT__mux;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__16__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__17__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__18__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__19__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__20__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__21__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__22__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__23__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__24__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__25__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__26__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__27__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__28__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__29__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__30__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        CData/*1:0*/ __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__31__KET____DOT__gen2__BRA__1__KET____DOT__redSum;
        VlUnpacked<CData/*0:0*/, 4> __PVT__issueTagsValid;
        VlUnpacked<CData/*5:0*/, 4> __PVT__issueTags;
        VlUnpacked<CData/*3:0*/, 64> __PVT__penc__DOT__gen__BRA__0__KET____DOT__s;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__0__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__1__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__2__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__3__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__4__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__5__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__6__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__7__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__8__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__9__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__10__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__11__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__12__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__0__KET____DOT__mux;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__13__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__14__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__15__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__16__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__16__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__17__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__17__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__18__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__18__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__19__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__19__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__20__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__20__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__21__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__21__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__22__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__22__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__23__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__23__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__24__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__24__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__25__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__25__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__26__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__26__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__27__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__27__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__28__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__28__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__29__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__29__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__30__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__30__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 2> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__31__KET____DOT__gen2__BRA__0__KET____DOT__mux;
        VlUnpacked<CData/*0:0*/, 3> __PVT__penc__DOT__gen__BRA__1__KET____DOT__genblk1__DOT__genblk1__BRA__31__KET____DOT__gen2__BRA__1__KET____DOT__mux;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v0;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v1;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v2;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v3;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v4;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v5;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v6;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v7;
        CData/*0:0*/ __VdlySet__OUT_issueTags__v4;
        CData/*0:0*/ __VdlySet__OUT_issueTags__v5;
        CData/*0:0*/ __VdlySet__OUT_issueTags__v6;
        CData/*0:0*/ __VdlySet__OUT_issueTags__v7;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v12;
        CData/*5:0*/ __VdlyVal__OUT_issueTags__v8;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v13;
        CData/*5:0*/ __VdlyVal__OUT_issueTags__v9;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v14;
        CData/*5:0*/ __VdlyVal__OUT_issueTags__v10;
        CData/*0:0*/ __VdlySet__OUT_issueTagsValid__v15;
        CData/*5:0*/ __VdlyVal__OUT_issueTags__v11;
        VL_OUT8(__PVT__OUT_issueTagsValid[4],0,0);
        VL_OUT8(__PVT__OUT_issueTags[4],5,0);
        VL_IN8(__PVT__IN_issueValid[4],0,0);
        QData/*63:0*/ free;
        CData/*0:0*/ __PVT__mispredWait;
        CData/*0:0*/ __Vdly__mispredWait;
        QData/*63:0*/ freeCom;
    };
    struct {
        QData/*63:0*/ __Vdly__freeCom;
        VL_IN8(__PVT__IN_commitValid[4],0,0);
        VL_IN8(__PVT__IN_commitNewest[4],0,0);
        VL_IN8(__PVT__IN_RAT_commitPrevTags[4],6,0);
        VL_IN8(__PVT__IN_commitTagDst[4],6,0);
        VL_IN8(__PVT__clk,0,0);
        VL_IN8(__PVT__rst,0,0);
        VL_IN8(__PVT__IN_mispr,0,0);
        VL_IN8(__PVT__IN_mispredFlush,0,0);
    };

    // INTERNAL VARIABLES
    VTop__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTop_TagBuffer(VTop__Syms* symsp, const char* v__name);
    ~VTop_TagBuffer();
    VL_UNCOPYABLE(VTop_TagBuffer);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __Vserialize(VerilatedSerialize& os);
    void __Vdeserialize(VerilatedDeserialize& os);
};


#endif  // guard
