// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VTop.h for the primary calling header

#include "VTop__pch.h"
#include "VTop_MemRTL__W200_N40.h"
#include "VTop__Syms.h"

void VTop_MemRTL__W200_N40___ctor_var_reset(VTop_MemRTL__W200_N40* vlSelf);

VTop_MemRTL__W200_N40::VTop_MemRTL__W200_N40(VTop__Syms* symsp, const char* v__name)
    : VerilatedModule{v__name}
    , vlSymsp{symsp}
 {
    // Reset structure values
    VTop_MemRTL__W200_N40___ctor_var_reset(this);
}

void VTop_MemRTL__W200_N40::__Vconfigure(bool first) {
    (void)first;  // Prevent unused variable warning
}

VTop_MemRTL__W200_N40::~VTop_MemRTL__W200_N40() {
}

// Savable
void VTop_MemRTL__W200_N40::__Vserialize(VerilatedSerialize& os) {
    uint64_t __Vcheckval = 0xcf0a66fa75cff8a8ULL;
    os << __Vcheckval;
    os << vlSymsp->_vm_contextp__;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        os<<__PVT__OUT_data[__Vi0];
    }
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        os<<__PVT__OUT_data1[__Vi0];
    }
    os<<__PVT__ce_reg;
    os<<__PVT__ce1_reg;
    os<<__PVT__we_reg;
    os<<__PVT__addr_reg;
    os<<__PVT__addr1_reg;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        os<<__PVT__data_reg[__Vi0];
    }
    os<<__PVT__wm_reg;
    os<<__VdlyVal__mem__v0;
    os<<__VdlyDim0__mem__v0;
    os<<__VdlySet__mem__v0;
    os<<__VdlyVal__mem__v1;
    os<<__VdlyDim0__mem__v1;
    os<<__VdlySet__mem__v1;
    os<<__VdlyVal__mem__v2;
    os<<__VdlyDim0__mem__v2;
    os<<__VdlySet__mem__v2;
    os<<__VdlyVal__mem__v3;
    os<<__VdlyDim0__mem__v3;
    os<<__VdlySet__mem__v3;
    os<<__VdlyVal__mem__v4;
    os<<__VdlyDim0__mem__v4;
    os<<__VdlySet__mem__v4;
    os<<__VdlyVal__mem__v5;
    os<<__VdlyDim0__mem__v5;
    os<<__VdlySet__mem__v5;
    os<<__VdlyVal__mem__v6;
    os<<__VdlyDim0__mem__v6;
    os<<__VdlySet__mem__v6;
    os<<__VdlyVal__mem__v7;
    os<<__VdlyDim0__mem__v7;
    os<<__VdlySet__mem__v7;
    os<<__VdlyVal__mem__v8;
    os<<__VdlyDim0__mem__v8;
    os<<__VdlySet__mem__v8;
    os<<__VdlyVal__mem__v9;
    os<<__VdlyDim0__mem__v9;
    os<<__VdlySet__mem__v9;
    os<<__VdlyVal__mem__v10;
    os<<__VdlyDim0__mem__v10;
    os<<__VdlySet__mem__v10;
    os<<__VdlyVal__mem__v11;
    os<<__VdlyDim0__mem__v11;
    os<<__VdlySet__mem__v11;
    os<<__VdlyVal__mem__v12;
    os<<__VdlyDim0__mem__v12;
    os<<__VdlySet__mem__v12;
    os<<__VdlyVal__mem__v13;
    os<<__VdlyDim0__mem__v13;
    os<<__VdlySet__mem__v13;
    os<<__VdlyVal__mem__v14;
    os<<__VdlyDim0__mem__v14;
    os<<__VdlySet__mem__v14;
    os<<__VdlyVal__mem__v15;
    os<<__VdlyDim0__mem__v15;
    os<<__VdlySet__mem__v15;
    os<<__VdlyVal__mem__v16;
    os<<__VdlyDim0__mem__v16;
    os<<__VdlySet__mem__v16;
    os<<__VdlyVal__mem__v17;
    os<<__VdlyDim0__mem__v17;
    os<<__VdlySet__mem__v17;
    os<<__VdlyVal__mem__v18;
    os<<__VdlyDim0__mem__v18;
    os<<__VdlySet__mem__v18;
    os<<__VdlyVal__mem__v19;
    os<<__VdlyDim0__mem__v19;
    os<<__VdlySet__mem__v19;
    os<<__VdlyVal__mem__v20;
    os<<__VdlyDim0__mem__v20;
    os<<__VdlySet__mem__v20;
    os<<__VdlyVal__mem__v21;
    os<<__VdlyDim0__mem__v21;
    os<<__VdlySet__mem__v21;
    os<<__VdlyVal__mem__v22;
    os<<__VdlyDim0__mem__v22;
    os<<__VdlySet__mem__v22;
    os<<__VdlyVal__mem__v23;
    os<<__VdlyDim0__mem__v23;
    os<<__VdlySet__mem__v23;
    os<<__VdlyVal__mem__v24;
    os<<__VdlyDim0__mem__v24;
    os<<__VdlySet__mem__v24;
    os<<__VdlyVal__mem__v25;
    os<<__VdlyDim0__mem__v25;
    os<<__VdlySet__mem__v25;
    os<<__VdlyVal__mem__v26;
    os<<__VdlyDim0__mem__v26;
    os<<__VdlySet__mem__v26;
    os<<__VdlyVal__mem__v27;
    os<<__VdlyDim0__mem__v27;
    os<<__VdlySet__mem__v27;
    os<<__VdlyVal__mem__v28;
    os<<__VdlyDim0__mem__v28;
    os<<__VdlySet__mem__v28;
    os<<__VdlyVal__mem__v29;
    os<<__VdlyDim0__mem__v29;
    os<<__VdlySet__mem__v29;
    os<<__VdlyVal__mem__v30;
    os<<__VdlyDim0__mem__v30;
    os<<__VdlySet__mem__v30;
    os<<__VdlyVal__mem__v31;
    os<<__VdlyDim0__mem__v31;
    os<<__VdlySet__mem__v31;
    os<<__VdlyVal__mem__v32;
    os<<__VdlyDim0__mem__v32;
    os<<__VdlySet__mem__v32;
    os<<__VdlyVal__mem__v33;
    os<<__VdlyDim0__mem__v33;
    os<<__VdlySet__mem__v33;
    os<<__VdlyVal__mem__v34;
    os<<__VdlyDim0__mem__v34;
    os<<__VdlySet__mem__v34;
    os<<__VdlyVal__mem__v35;
    os<<__VdlyDim0__mem__v35;
    os<<__VdlySet__mem__v35;
    os<<__VdlyVal__mem__v36;
    os<<__VdlyDim0__mem__v36;
    os<<__VdlySet__mem__v36;
    os<<__VdlyVal__mem__v37;
    os<<__VdlyDim0__mem__v37;
    os<<__VdlySet__mem__v37;
    os<<__VdlyVal__mem__v38;
    os<<__VdlyDim0__mem__v38;
    os<<__VdlySet__mem__v38;
    os<<__VdlyVal__mem__v39;
    os<<__VdlyDim0__mem__v39;
    os<<__VdlySet__mem__v39;
    os<<__VdlyVal__mem__v40;
    os<<__VdlyDim0__mem__v40;
    os<<__VdlySet__mem__v40;
    os<<__VdlyVal__mem__v41;
    os<<__VdlyDim0__mem__v41;
    os<<__VdlySet__mem__v41;
    os<<__VdlyVal__mem__v42;
    os<<__VdlyDim0__mem__v42;
    os<<__VdlySet__mem__v42;
    os<<__VdlyVal__mem__v43;
    os<<__VdlyDim0__mem__v43;
    os<<__VdlySet__mem__v43;
    os<<__VdlyVal__mem__v44;
    os<<__VdlyDim0__mem__v44;
    os<<__VdlySet__mem__v44;
    os<<__VdlyVal__mem__v45;
    os<<__VdlyDim0__mem__v45;
    os<<__VdlySet__mem__v45;
    os<<__VdlyVal__mem__v46;
    os<<__VdlyDim0__mem__v46;
    os<<__VdlySet__mem__v46;
    os<<__VdlyVal__mem__v47;
    os<<__VdlyDim0__mem__v47;
    os<<__VdlySet__mem__v47;
    os<<__VdlyVal__mem__v48;
    os<<__VdlyDim0__mem__v48;
    os<<__VdlySet__mem__v48;
    os<<__VdlyVal__mem__v49;
    os<<__VdlyDim0__mem__v49;
    os<<__VdlySet__mem__v49;
    os<<__VdlyVal__mem__v50;
    os<<__VdlyDim0__mem__v50;
    os<<__VdlySet__mem__v50;
    os<<__VdlyVal__mem__v51;
    os<<__VdlyDim0__mem__v51;
    os<<__VdlySet__mem__v51;
    os<<__VdlyVal__mem__v52;
    os<<__VdlyDim0__mem__v52;
    os<<__VdlySet__mem__v52;
    os<<__VdlyVal__mem__v53;
    os<<__VdlyDim0__mem__v53;
    os<<__VdlySet__mem__v53;
    os<<__VdlyVal__mem__v54;
    os<<__VdlyDim0__mem__v54;
    os<<__VdlySet__mem__v54;
    os<<__VdlyVal__mem__v55;
    os<<__VdlyDim0__mem__v55;
    os<<__VdlySet__mem__v55;
    os<<__VdlyVal__mem__v56;
    os<<__VdlyDim0__mem__v56;
    os<<__VdlySet__mem__v56;
    os<<__VdlyVal__mem__v57;
    os<<__VdlyDim0__mem__v57;
    os<<__VdlySet__mem__v57;
    os<<__VdlyVal__mem__v58;
    os<<__VdlyDim0__mem__v58;
    os<<__VdlySet__mem__v58;
    os<<__VdlyVal__mem__v59;
    os<<__VdlyDim0__mem__v59;
    os<<__VdlySet__mem__v59;
    os<<__VdlyVal__mem__v60;
    os<<__VdlyDim0__mem__v60;
    os<<__VdlySet__mem__v60;
    os<<__VdlyVal__mem__v61;
    os<<__VdlyDim0__mem__v61;
    os<<__VdlySet__mem__v61;
    os<<__VdlyVal__mem__v62;
    os<<__VdlyDim0__mem__v62;
    os<<__VdlySet__mem__v62;
    os<<__VdlyVal__mem__v63;
    os<<__VdlyDim0__mem__v63;
    os<<__VdlySet__mem__v63;
    for (int __Vi0 = 0; __Vi0 < 64; ++__Vi0) {
        for (int __Vi1 = 0; __Vi1 < 16; ++__Vi1) {
            os<<mem[__Vi0][__Vi1];
        }
    }
    os<<__PVT__clk;
    os<<__PVT__IN_nce;
    os<<__PVT__IN_nwe;
    os<<__PVT__IN_addr;
    os<<__PVT__IN_nce1;
    os<<__PVT__IN_addr1;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        os<<__PVT__IN_data[__Vi0];
    }
    os<<__PVT__IN_wm;
}
void VTop_MemRTL__W200_N40::__Vdeserialize(VerilatedDeserialize& os) {
    uint64_t __Vcheckval = 0xcf0a66fa75cff8a8ULL;
    os.readAssert(__Vcheckval);
    os >> vlSymsp->_vm_contextp__;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        os>>__PVT__OUT_data[__Vi0];
    }
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        os>>__PVT__OUT_data1[__Vi0];
    }
    os>>__PVT__ce_reg;
    os>>__PVT__ce1_reg;
    os>>__PVT__we_reg;
    os>>__PVT__addr_reg;
    os>>__PVT__addr1_reg;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        os>>__PVT__data_reg[__Vi0];
    }
    os>>__PVT__wm_reg;
    os>>__VdlyVal__mem__v0;
    os>>__VdlyDim0__mem__v0;
    os>>__VdlySet__mem__v0;
    os>>__VdlyVal__mem__v1;
    os>>__VdlyDim0__mem__v1;
    os>>__VdlySet__mem__v1;
    os>>__VdlyVal__mem__v2;
    os>>__VdlyDim0__mem__v2;
    os>>__VdlySet__mem__v2;
    os>>__VdlyVal__mem__v3;
    os>>__VdlyDim0__mem__v3;
    os>>__VdlySet__mem__v3;
    os>>__VdlyVal__mem__v4;
    os>>__VdlyDim0__mem__v4;
    os>>__VdlySet__mem__v4;
    os>>__VdlyVal__mem__v5;
    os>>__VdlyDim0__mem__v5;
    os>>__VdlySet__mem__v5;
    os>>__VdlyVal__mem__v6;
    os>>__VdlyDim0__mem__v6;
    os>>__VdlySet__mem__v6;
    os>>__VdlyVal__mem__v7;
    os>>__VdlyDim0__mem__v7;
    os>>__VdlySet__mem__v7;
    os>>__VdlyVal__mem__v8;
    os>>__VdlyDim0__mem__v8;
    os>>__VdlySet__mem__v8;
    os>>__VdlyVal__mem__v9;
    os>>__VdlyDim0__mem__v9;
    os>>__VdlySet__mem__v9;
    os>>__VdlyVal__mem__v10;
    os>>__VdlyDim0__mem__v10;
    os>>__VdlySet__mem__v10;
    os>>__VdlyVal__mem__v11;
    os>>__VdlyDim0__mem__v11;
    os>>__VdlySet__mem__v11;
    os>>__VdlyVal__mem__v12;
    os>>__VdlyDim0__mem__v12;
    os>>__VdlySet__mem__v12;
    os>>__VdlyVal__mem__v13;
    os>>__VdlyDim0__mem__v13;
    os>>__VdlySet__mem__v13;
    os>>__VdlyVal__mem__v14;
    os>>__VdlyDim0__mem__v14;
    os>>__VdlySet__mem__v14;
    os>>__VdlyVal__mem__v15;
    os>>__VdlyDim0__mem__v15;
    os>>__VdlySet__mem__v15;
    os>>__VdlyVal__mem__v16;
    os>>__VdlyDim0__mem__v16;
    os>>__VdlySet__mem__v16;
    os>>__VdlyVal__mem__v17;
    os>>__VdlyDim0__mem__v17;
    os>>__VdlySet__mem__v17;
    os>>__VdlyVal__mem__v18;
    os>>__VdlyDim0__mem__v18;
    os>>__VdlySet__mem__v18;
    os>>__VdlyVal__mem__v19;
    os>>__VdlyDim0__mem__v19;
    os>>__VdlySet__mem__v19;
    os>>__VdlyVal__mem__v20;
    os>>__VdlyDim0__mem__v20;
    os>>__VdlySet__mem__v20;
    os>>__VdlyVal__mem__v21;
    os>>__VdlyDim0__mem__v21;
    os>>__VdlySet__mem__v21;
    os>>__VdlyVal__mem__v22;
    os>>__VdlyDim0__mem__v22;
    os>>__VdlySet__mem__v22;
    os>>__VdlyVal__mem__v23;
    os>>__VdlyDim0__mem__v23;
    os>>__VdlySet__mem__v23;
    os>>__VdlyVal__mem__v24;
    os>>__VdlyDim0__mem__v24;
    os>>__VdlySet__mem__v24;
    os>>__VdlyVal__mem__v25;
    os>>__VdlyDim0__mem__v25;
    os>>__VdlySet__mem__v25;
    os>>__VdlyVal__mem__v26;
    os>>__VdlyDim0__mem__v26;
    os>>__VdlySet__mem__v26;
    os>>__VdlyVal__mem__v27;
    os>>__VdlyDim0__mem__v27;
    os>>__VdlySet__mem__v27;
    os>>__VdlyVal__mem__v28;
    os>>__VdlyDim0__mem__v28;
    os>>__VdlySet__mem__v28;
    os>>__VdlyVal__mem__v29;
    os>>__VdlyDim0__mem__v29;
    os>>__VdlySet__mem__v29;
    os>>__VdlyVal__mem__v30;
    os>>__VdlyDim0__mem__v30;
    os>>__VdlySet__mem__v30;
    os>>__VdlyVal__mem__v31;
    os>>__VdlyDim0__mem__v31;
    os>>__VdlySet__mem__v31;
    os>>__VdlyVal__mem__v32;
    os>>__VdlyDim0__mem__v32;
    os>>__VdlySet__mem__v32;
    os>>__VdlyVal__mem__v33;
    os>>__VdlyDim0__mem__v33;
    os>>__VdlySet__mem__v33;
    os>>__VdlyVal__mem__v34;
    os>>__VdlyDim0__mem__v34;
    os>>__VdlySet__mem__v34;
    os>>__VdlyVal__mem__v35;
    os>>__VdlyDim0__mem__v35;
    os>>__VdlySet__mem__v35;
    os>>__VdlyVal__mem__v36;
    os>>__VdlyDim0__mem__v36;
    os>>__VdlySet__mem__v36;
    os>>__VdlyVal__mem__v37;
    os>>__VdlyDim0__mem__v37;
    os>>__VdlySet__mem__v37;
    os>>__VdlyVal__mem__v38;
    os>>__VdlyDim0__mem__v38;
    os>>__VdlySet__mem__v38;
    os>>__VdlyVal__mem__v39;
    os>>__VdlyDim0__mem__v39;
    os>>__VdlySet__mem__v39;
    os>>__VdlyVal__mem__v40;
    os>>__VdlyDim0__mem__v40;
    os>>__VdlySet__mem__v40;
    os>>__VdlyVal__mem__v41;
    os>>__VdlyDim0__mem__v41;
    os>>__VdlySet__mem__v41;
    os>>__VdlyVal__mem__v42;
    os>>__VdlyDim0__mem__v42;
    os>>__VdlySet__mem__v42;
    os>>__VdlyVal__mem__v43;
    os>>__VdlyDim0__mem__v43;
    os>>__VdlySet__mem__v43;
    os>>__VdlyVal__mem__v44;
    os>>__VdlyDim0__mem__v44;
    os>>__VdlySet__mem__v44;
    os>>__VdlyVal__mem__v45;
    os>>__VdlyDim0__mem__v45;
    os>>__VdlySet__mem__v45;
    os>>__VdlyVal__mem__v46;
    os>>__VdlyDim0__mem__v46;
    os>>__VdlySet__mem__v46;
    os>>__VdlyVal__mem__v47;
    os>>__VdlyDim0__mem__v47;
    os>>__VdlySet__mem__v47;
    os>>__VdlyVal__mem__v48;
    os>>__VdlyDim0__mem__v48;
    os>>__VdlySet__mem__v48;
    os>>__VdlyVal__mem__v49;
    os>>__VdlyDim0__mem__v49;
    os>>__VdlySet__mem__v49;
    os>>__VdlyVal__mem__v50;
    os>>__VdlyDim0__mem__v50;
    os>>__VdlySet__mem__v50;
    os>>__VdlyVal__mem__v51;
    os>>__VdlyDim0__mem__v51;
    os>>__VdlySet__mem__v51;
    os>>__VdlyVal__mem__v52;
    os>>__VdlyDim0__mem__v52;
    os>>__VdlySet__mem__v52;
    os>>__VdlyVal__mem__v53;
    os>>__VdlyDim0__mem__v53;
    os>>__VdlySet__mem__v53;
    os>>__VdlyVal__mem__v54;
    os>>__VdlyDim0__mem__v54;
    os>>__VdlySet__mem__v54;
    os>>__VdlyVal__mem__v55;
    os>>__VdlyDim0__mem__v55;
    os>>__VdlySet__mem__v55;
    os>>__VdlyVal__mem__v56;
    os>>__VdlyDim0__mem__v56;
    os>>__VdlySet__mem__v56;
    os>>__VdlyVal__mem__v57;
    os>>__VdlyDim0__mem__v57;
    os>>__VdlySet__mem__v57;
    os>>__VdlyVal__mem__v58;
    os>>__VdlyDim0__mem__v58;
    os>>__VdlySet__mem__v58;
    os>>__VdlyVal__mem__v59;
    os>>__VdlyDim0__mem__v59;
    os>>__VdlySet__mem__v59;
    os>>__VdlyVal__mem__v60;
    os>>__VdlyDim0__mem__v60;
    os>>__VdlySet__mem__v60;
    os>>__VdlyVal__mem__v61;
    os>>__VdlyDim0__mem__v61;
    os>>__VdlySet__mem__v61;
    os>>__VdlyVal__mem__v62;
    os>>__VdlyDim0__mem__v62;
    os>>__VdlySet__mem__v62;
    os>>__VdlyVal__mem__v63;
    os>>__VdlyDim0__mem__v63;
    os>>__VdlySet__mem__v63;
    for (int __Vi0 = 0; __Vi0 < 64; ++__Vi0) {
        for (int __Vi1 = 0; __Vi1 < 16; ++__Vi1) {
            os>>mem[__Vi0][__Vi1];
        }
    }
    os>>__PVT__clk;
    os>>__PVT__IN_nce;
    os>>__PVT__IN_nwe;
    os>>__PVT__IN_addr;
    os>>__PVT__IN_nce1;
    os>>__PVT__IN_addr1;
    for (int __Vi0 = 0; __Vi0 < 16; ++__Vi0) {
        os>>__PVT__IN_data[__Vi0];
    }
    os>>__PVT__IN_wm;
}
